[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "testgrad"
version = "0.1.0"
dependencies = []

[tool.setuptools]
include-package-data = true
packages = ["testgrad"]